# Homepage


# Mod page
InfoFormLegend: Edit QuickMod Info
CantEdit: You are not allowed to edit this QuickMod.
ModPageTitle modName@Text: QuickMod Page for #{modName}
EditModPageTitle modName@Text: Edit QuickMod for #{modName}
ModInfoTable: Mod Information
ModUidLabel: UID
ModUidTooltip: An ID for the mod. This should be the same for all of this mod's QuickMod files.
ModNameLabel: Mod Name
ModCatsLabel: Categories
ModTagsLabel: Tags
ModAuthorsLabel: Authors
ModWebsiteLabel: Website
ModIssuesUrlLabel: Bug Tracker
ModDonationsUrlLabel: Donations

VsnNameLabel: Version
VsnTypeLabel: Version Type
VsnUrlLabel: Download URL

QuickModUpdated: The QuickMod has been updated successfully.


# General stuff
SubmitBtn: Submit
SaveBtn: Save

