# Homepage


# Mod page
CantEdit: You are not allowed to edit this QuickMod.
ModPageTitle modName@Text: QuickMod Page for #{modName}
ModInfoTable: Mod Information
ModUidLabel: UID
ModNameLabel: Mod Name
ModCatsLabel: Categories
ModTagsLabel: Tags
ModAuthorsLabel: Authors
ModWebsiteLabel: Website
ModIssuesUrlLabel: Bug Tracker
ModDonationsUrlLabel: Donations

VsnNameLabel: Version
VsnTypeLabel: Version Type
VsnUrlLabel: Download URL


# General stuff
SubmitBtn: Submit

