# Homepage


# Navbar
NavNew: New QuickMod
NavSubNew: Create a new QuickMod
NavBrowse: Browse
NavSubBrowse: Browse QuickMods
NavLogin: Log In
NavSubLogin: Log in to your account
NavLogout: Log Out
NavSubLogout: Log out of your account


# QuickMod list
ModListUid: UID
ModListName: Name


# Mod page
InfoFormLegend: Edit QuickMod Info
AddFormLegend: New QuickMod
CantEdit: You are not allowed to edit this QuickMod.
EditQuickMod: Edit QuickMod
ModPageTitle modName@Text: QuickMod Page for #{modName}
EditModPageTitle modName@Text: Edit QuickMod for #{modName}
ModInfoTable: Mod Information

ModUidLabel: UID
ModUidTip: An ID for the mod. This should be the same for all of this mod's QuickMod files.
ModNameLabel: Mod Name
ModNameTip: The mod's name.
ModCatsLabel: Categories
ModCatsTip: A list of categories for the mod.
ModTagsLabel: Tags
ModTagsTip: A list of tags for the mod.
ModAuthorsLabel: Authors
ModAuthorsTip: A list of the mod's authors.
ModWebsiteLabel: Website
ModWebsiteTip: The mod's website.
ModIssuesUrlLabel: Bug Tracker
ModDonationsUrlLabel: Donations

QuickModUpdated: The QuickMod has been updated successfully.


# Version page
AddVsnTitle: Add Version
EditVsnTitle: Edit Version

VsnNameLabel: Version
VsnNameTip: The version's name. For example: "1.3.3.7"
VsnTypeLabel: Version Type
VsnTypeTip: The version's release type. For example: Alpha, Beta, Release, Stable, etc.
VsnDlTypeLabel: Download Type
VsnDlTypeTip: Specifies how to download this version. For a complete description of all the options, see the QuickMod docs.
VsnInstTypeLabel: Install Type
VsnInstTypeTip: Specifies how to install this version. For a complete description of all the options, see the QuickMod docs.
VsnUrlLabel: Download URL
VsnUrlTip: The URL to download the version from.

VsnDirectDl: Direct Download
VsnParallelDl: Parallel Browser Download
VsnSequentialDl: Sequential Browser Download

VsnForgeModInst: Forge Mod
VsnFCoreModInst: Forge Core Mod
VsnConfigPackInst: Config Pack
VsnGroupModInst: Group Mod (For mod packs)

VersionUpdated: The version has been updated successfully.


# General stuff
SubmitBtn: Submit
SaveBtn: Save

