Default: &defaults
  user: quickmod-io
  password: quickmod-io
  host: localhost
  port: 5432
  database: quickmod-io
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: quickmod-io_test
  user: quickmod-io_test
  <<: *defaults

Staging:
  database: quickmod-io_staging
  user: quickmod-io_staging
  poolsize: 100
  <<: *defaults

Production:
  poolsize: 100
  <<: *defaults
